# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dm-4-cat',
                'doc_host': 'https://Chavelanda.github.io',
                'git_url': 'https://github.com/Chavelanda/dm-4-cat',
                'lib_path': 'dm_4_cat'},
  'syms': { 'dm_4_cat.core': {'dm_4_cat.core.foo': ('core.html#foo', 'dm_4_cat/core.py')},
            'dm_4_cat.preprocessing': {'dm_4_cat.preprocessing.foo': ('preprocessing.html#foo', 'dm_4_cat/preprocessing.py')}}}
